[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  node_bundler = "esbuild"
